### ISSUE TITLE
Upgrade to fossa-cli v.3 should have been a major version bump

### ISSUE THREAD

**Issue by dej611** [fossa-contrib/fossa-action#247]
I was using your `fossa-action` before and everything was working fine with a config file set to version 2:

```
- name: Run FOSSA scan and upload build data
   uses: fossa-contrib/fossa-action@v1
   with:
       fossa-api-key: ...
```

Then few days ago the CI check started failing and I noticed this warning:

```
[ WARN] 
  Incompatible [.fossa.yml] found! Expecting `version: 3`; found `version: 2`
  Documentation for the new config file format can be found here:
      fossas/fossa-cli@v3.0.4/docs/references/files/fossa-yml.md
```

Now, this is a breaking change and bumping from 1.1.4 to 1.1.5 **was not the right** thing to do.

Anyway I managed to solve, so I'll report there the process and some other issues for others with the same problem:

I haven't found a way to make it work to v.3, so I've tried to use a specific version down to the patch before the v3 upgrade:

```yaml
- name: Run FOSSA scan and upload build data
   uses: fossa-contrib/fossa-action@v1.1.4
   with:
       fossa-api-key: ...
```

And the CI reported the error:

```
Run fossa-contrib/fossa-action@v1.1.4
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/3d626ddd-dd4a-48fe-9887-d85e3caf9f52 -f /home/runner/work/_temp/c45aa0cb-4f4f-46e7-bd55-d3e99740f801
/usr/bin/tar: This does not look like a tar archive
/usr/bin/tar: Skipping to next header
/usr/bin/tar: Exiting with failure status due to previous errors
```

The only thing that worked was to use a commit pointer:

```yaml
- name: Run FOSSA scan and upload build data
   uses: fossa-contrib/fossa-action@e015db70fcadbf6316ed25b4c0c264d78d971714
   with:
       fossa-api-key: ...
```
